### ISSUE TITLE
Incorrect Intermol Installation Folder

### ISSUE THREAD

**Issue by KelechiO** [shirtsgroup/InterMol#270]
Hello,
I attempted to download Intermol however only the README file was in the folder.
Please has the location of the Intermol Installation folder changed?

**Comment by swails** [comment]
You need to checkout the develop branch.

```
git clone https://github.com/shirtsgroup/InterMol.git
git checkout develop
```

The master branch is empty (as you noticed).

**Comment by KelechiO** [comment]
Please I got the following error when I attempted installing Intermol using the development branch:


*********************************************************
This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

**Comment by ctk3b** [comment]
Once you're in the InterMol top level directory, try installing with pip:
```
pip install -e .
```

Currently, it will unfortunately try to install numpy and parmed via pip due to the requirements file.

If you are using conda, you can easily install these with:
```
conda install numpy
conda install -c omnia parmed
```

If you are not, I would recommend removing the the `parmed` line from `requirements.txt` and then trying `pip install -e .` again.

**Comment by swails** [comment]
ParmEd should be pip-installable:

```
$ pip search parmed
ParmEd     - Amber parameter file editor
  INSTALLED: 2.2.3
  LATEST:    2.1.10
```

**Comment by ctk3b** [comment]
Oh excellent! Good to know.
