### ISSUE TITLE
error when converting gromacs to desmond

### ISSUE THREAD

**Issue by Marcela51** [shirtsgroup/InterMol#290]
Hello,
I have issued the following command:
python /usr/local/packages/InterMol/intermol/convert.py --gro_in forworkshop.gro topol.top --desmond 

topol.top calls charmm22star FF and several itp files. 

I get the following error:

Beginning InterMol conversion
WARNING 2016-11-27 14:01:19 Lookup failed for dihedral: ['C', 'CT1', 'NH1', 'O']
Traceback (most recent call last):

Is there a solution for this? thanks, Marcela

**Comment by mrshirts** [comment]
Can you post the .top and .gro file to debug?

**Comment by Marcela51** [comment]
I had to email them because I have promised confidentiality. Please let me know if you got them.
Or is it only you and your group that can see the issue tracker?

Marcela

**Comment by Marcela51** [comment]
[example.zip](https://github.com/shirtsgroup/InterMol/files/614964/example.zip)







[charmm22star.ff.tar.gz](https://github.com/shirtsgroup/InterMol/files/614938/charmm22star.ff.tar.gz)

**Comment by mrshirts** [comment]
The github issue tracker is not private.  I did get the email and will be working on it this afternoon.

**Comment by Marcela51** [comment]
thanks, 
Marcela

**Comment by ctk3b** [comment]
I'll check this tonight but this might be fixed by my most recent pull request which added a few wildcard cases to dihedral type resolution.

**Comment by ctk3b** [comment]
#287

**Comment by mrshirts** [comment]
Marcela, did you try to repull the code with Cristoph's fix and see if it works on this case (am prepping stuff for lecture tomorrow, will be working on InterMol after that).

**Comment by Marcela51** [comment]
thanks, I will try. 

Marcela

**Comment by Marcela51** [comment]
It work after the git pull, thanks so much, my apologies.

Marcela

**Comment by mrshirts** [comment]
Great! Keep examples coming.  I'm sure that there will be issues that come up when people try new configurations, and we will try to fix them.

**Comment by Marcela51** [comment]
This converted to cms, but it did not compare the energies,and gave the following error:
Program gmx grompp, VERSION 5.1.3
Source code file: /opt/packages/gromacs-5.1.3/src/gromacs/gmxpreprocess/toppush.c, line: 908

Fatal error:
Unknown bond_atomtype cn9

thanks, Marcela

**Comment by mrshirts** [comment]
OK, the basic reason the energy evaluate failed is clear.  I'll have to think a little about how to automate it. 

The default .mdp that is being used to run the energy comparison for the inputs does not say where to look for the .itp. Normally, where to look for .itp files would be stated in the "include = " keyword, but since it's a default .mdp, this wouldn't be present. it would be OK if they were in the main directory as itp, but they are in a separate folder.  If the charmm22star.ff directory was placed in the source gromacs directory, it should work.

I'm trying this now, and I am having a hard time getting it to run in gromacs alone.  For example, if I run
 gmx grompp  -f start.mdp -c forworkshop.gro -p topol.top -o r.tpr 

from the command line, I get the same error.  Do you get that error when you try to run it from the command line? If so, there's something off about those files.

**Comment by Marcela51** [comment]
yes, even from the command line I get
Fatal error:
Unknown bond_atomtype cn9

 thanks, 
Marcela 

On Nov 2

**Comment by mrshirts** [comment]
Right, so it's a problem with the way the files are set up originally. Perhaps if the charmm22star.ff files are copied into the  shared directory? If not, then something is wrong with the file setup -- I see that cn9 is indeed defined in them.
